import com.navigatingcancer.patientinfo.domain.PatientInfo;
import com.navigatingcancer.healthtracker.api.processor.model.HealthTracker;
import com.navigatingcancer.healthtracker.api.data.model.CheckInResult.ResultType;
import com.navigatingcancer.healthtracker.api.data.model.HealthTrackerStatusCategory;

dialect  "mvel"

/*********** Severity ***********/

rule "Very Severe, Severe, or Moderate Side Effect"
     
    when
            $ht:HealthTracker(
            	getCheckInAggregator().countSideAffects(0, "Severity", "pain", "2,3,4") > 0
            )
    then
    	$ht.getCheckInAggregator().addSymptom(0, "Severity", "2,3,4")
        $ht.getHealthTrackerStatus().updateIfHigherPriorityCategory(HealthTrackerStatusCategory.TRIAGE)

end


rule "Pain Severity of 4, 5, 6, 7, 8, 9, 10"

    when
            $ht:HealthTracker(
                getCheckInAggregator().countSideAffects(0, "painSeverity", "4,5,6,7,8,9,10") > 0
            )
    then
    	$ht.getCheckInAggregator().addSymptom(0, "painSeverity", "4,5,6,7,8,9,10")
        $ht.getHealthTrackerStatus().updateIfHigherPriorityCategory(HealthTrackerStatusCategory.TRIAGE)

end

