apiVersion: {{ .Values.apiVersions.ExternalSecret }}
kind: ExternalSecret
metadata:
  name: health-tracker-rest-secret{{ if .Values.canaryRelease}}-canary{{ end }}

{{ if eq .Values.apiVersions.ExternalSecret "external-secrets.io/v1beta1" }}
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .Values.env.springProfile }}/ht-api
    - extract:
        key: {{ .Values.env.springProfile }}/shared
    - extract:
        key: {{ .Values.env.springProfile }}/ht-server-docdb

{{ else if eq .Values.apiVersions.ExternalSecret "kubernetes-client.io/v1" }}
secretDescriptor:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.env.springProfile }}/ht-api
    - {{ .Values.env.springProfile }}/shared
    - {{ .Values.env.springProfile }}/ht-server-docdb
{{ end }}
