{{- if .Values.serviceAccountRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ht-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ht-api.name" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleArn }}
automountServiceAccountToken: true
{{- end }}
